spring:
  config:
    import: "optional:configserver:http://config-service:8088"
    activate:
      on-profile: docker

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:news_system_auth}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    virtual-host: /
    port: 15672
    username: guest
    password: guest

mp:
  rabbitmq:
    queue: user.queue
    delay:
      routing-key: user.delayed.queue
      exchange: user.delay.exchange

jwt:
  token:
    secret: newssystemauth
    expired: 3600000
---
spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:8088"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:news_system_auth}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    virtual-host: /
    port: 15672
    username: guest
    password: guest

mp:
  rabbitmq:
    queue: user.queue
    delay:
      routing-key: user.delayed.queue
      exchange: user.delay.exchange

jwt:
  token:
    secret: newssystemauth
    expired: 3600000
