version: '3.9'

services:
  eureka-server:
    build:
      dockerfile: eureka-server/Dockerfile
      context: ./
    image: cyjay96/eureka-server
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - postgres-network
    restart: unless-stopped

  api-gateway:
    build:
      dockerfile: api-gateway/Dockerfile
      context: ./
    image: cyjay96/api-gateway
    ports:
      - "8765:8765"
    environment:
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - postgres-network
    restart: unless-stopped

  news-service-api:
    build:
      dockerfile: news-service/Dockerfile
      context: ./
    image: cyjay96/news-service-api
    ports:
      - "8081:8081"
    environment:
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://eureka-server:8761/eureka/
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: news_system_dev
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - eureka-server
    networks:
      - postgres-network
    restart: unless-stopped

  auth-service-api:
    build:
      dockerfile: auth-service/Dockerfile
      context: ./
    image: cyjay96/auth-service-api
    ports:
      - "8082:8082"
    environment:
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://eureka-server:8761/eureka/
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: news_system_auth
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - eureka-server
    networks:
      - postgres-network
    restart: unless-stopped

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    networks:
      - postgres-network
    restart: unless-stopped

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - postgres-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"

networks:
  postgres-network:
