server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: news-service
  rabbitmq:
    host: localhost
    virtual-host: /
    port: 15672
    username: guest
    password: guest

mp:
  rabbitmq:
    queue: user.queue
    delay:
      routing-key: user.delayed.queue
      exchange: user.delay.exchange

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE:http://localhost:8761/eureka}
